OnlineShopping/Controllers/HomeController.cs
using OnlineShopping.DAL;
using OnlineShopping.Filters;
using OnlineShopping.Repository;
using System;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace OnlineShopping.Controllers
{
    [FrontPageActionFilter]
    public class HomeController : Controller
    {
        #region Other Class references ... // Instance on Unit of Work 
        public GenericUnitOfWork _unitOfWork = new GenericUnitOfWork();
        #endregion
        /// <summary>
        /// Home Page
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            ViewBag.Products = _unitOfWork.GetRepositoryInstance<Tbl_Product>().GetListByParameter(i => i.IsDelete == false && i.IsActive == true).ToList();
            return View();
        }

        #region Disposing UnitOfWork Context ...
        protected override void Dispose(bool disposing)
        {
            _unitOfWork.Dispose();
            base.Dispose(disposing);
        }
        #endregion
    }
}

OnlineShopping/Controllers/SearchController.cs
using OnlineShopping.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShopping.DAL;
using System.Data.SqlClient;
using System.Data;
using OnlineShopping.Filters;
namespace OnlineShopping.Controllers
{
    [FrontPageActionFilter]
    public class SearchController : Controller
    {
        #region Other Class references ...         
        // Instance on Unit of Work         
        public GenericUnitOfWork _unitOfWork = new GenericUnitOfWork();
        private int _memberId;
        public int memberId
        {
            get { return Convert.ToInt32(Session["MemberId"]); }
            set { _memberId = Convert.ToInt32(Session["MemberId"]); }
        }
        #endregion  
        /// <summary>
        /// Search Result Page
        /// </summary>
        /// <param name="searchKey"></param>
        /// <returns></returns>
        public ActionResult Index(string searchKey = "")
        {
            ViewBag.searchKey = searchKey; List<USP_Search_Result> sr = _unitOfWork.GetRepositoryInstance<USP_Search_Result>().GetResultBySqlProcedure("USP_Search @searchKey", new SqlParameter("searchKey", SqlDbType.VarChar) { Value = searchKey }).ToList();
            return View(sr);
        }

        /// <summary>
        /// Product Detail
        /// </summary>
        /// <param name="pId"></param>
        /// <returns></returns>
        public ActionResult ProductDetail(int pId)
        {
            Tbl_Product pd = _unitOfWork.GetRepositoryInstance<Tbl_Product>().GetFirstOrDefault(pId);
            ViewBag.SimilarProducts = _unitOfWork.GetRepositoryInstance<Tbl_Product>().GetListByParameter(i => i.CategoryId == pd.CategoryId).ToList();
            return View(pd);
        }
        
    }
}

OnlineShopping/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

OnlineShopping/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OnlineShopping/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Online Shopping : Home Page";
    Layout = "~/Views/Shared/_FrontLayout.cshtml";
    List<OnlineShopping.DAL.Tbl_Product> Products = (List<OnlineShopping.DAL.Tbl_Product>)ViewBag.Products;
}
<style>
    .profPerson .ProfImg {
        width: 240px;
        height: 153px;
    }

    .assistImg .transition {
        height: 107px;
    }
</style> <div class="homeSlider">
    <div class="bannerSlider" style="background: url(../images/HomePageBanner1.png) no-repeat center center;">     </div>     <div class="searchOnline clearfix">
        <div class="container">
            <div class="olContent fl"><h2>Search Product/Category</h2></div>
            <div class="olSearch fr">
                @using (Html.BeginForm("Index", "Search", FormMethod.Post))
                {
                    <div>
                        <input type="text" placeholder="Enter Keywords" onkeypress="return onlynumericOrCharacter();" name="searchKey" class="inputComn houseText">
                    </div>
                    <div class="searchIcon">
                        <button type="button" class="searchBtn" onclick="$(this).parent().parent().submit();">
                            <img src="/images/searchIcon.png" alt="img">
                        </button>
                    </div>
                }
            </div>
        </div>
    </div>
</div> <!--End Slider--> <!--Start Featured Professionals--> <div class="featuredProfessionals">
    <div class="container">
        <h1>Products</h1>
        <div class="professionSLider">
            <div class="profSlider">
                @foreach (var product in Products)
                {
                    <div class="item">
                        <div class="profPerson">

                            @if (File.Exists(Server.MapPath(System.Configuration.ConfigurationManager.AppSettings["ProductImage"] + "Medium/" + product.ProductId + "_" + product.ProductImage)))
                            {
                                <img class="ProfImg" title="Click to view product detail" style="cursor:pointer;" onclick="window.location.href ='/search/productdetail?pId=@product.ProductId'" src="@(System.Configuration.ConfigurationManager.AppSettings["ProductImage"] + "Medium/" + product.ProductId+"_"+product.ProductImage)" />
                            }
                            else
                            {
                                <img class="ProfImg" title="Click to view product detail" style="cursor:pointer;" onclick="window.location.href ='/search/productdetail?pId=@product.ProductId'" src="@(System.Configuration.ConfigurationManager.AppSettings["ProductImage_Default_Medium"])" alt="" />
                            }
                            <div class="profMid clearfix">
                                <h2 title="Click to view product detail" style="cursor:pointer;"><a href="/search/productdetail?pId=@product.ProductId">  @product.ProductName</a></h2>                                 <div class="leftprof fl">
                                    <text>
                                        Category <a title="Products of this category" style="cursor:pointer;" href="/search?searchkey=@product.Tbl_Category.CategoryName">@product.Tbl_Category.CategoryName</a>
                                    </text>
                                </div>
                            </div>
                        </div>
                        <div class="profLast clearfix">
                            <div class="leftprofLast fl"><h4>Price</h4></div>
                            <div class="rightprofLast fr"><h5>@(product.Price)</h5></div>
                        </div>
                    </div>
                }
            </div>
            <div class="left-symbol"><img src="/Images/sliderRightarrow.png" alt="images"></div>             <div class="right-symbol"><img src="/Images/sliderLeftarrow.png" alt="images"></div>
        </div>
    </div>
</div>
<!--End product Professionals-->
@section Scripts{
    <script>
      window.onload = function () {
      if ('@Request.QueryString["returnUrl"]' != '') {
       $('#returnUrl').val('@Request.QueryString["returnUrl"]')
       $('.loginpopup').trigger('click');
    }

    if ('@(Request.UrlReferrer !=null ?Request.UrlReferrer.AbsolutePath.ToLower():"")' == '/account/resetpassword') {
                   $('.loginpopup').trigger('click');
    }
                          if('@TempData["VerificationLinlMsg"]'!='')             {
     swal('@TempData["VerificationLinlMsg"]', '', 'success');
     }         }     </script> }  